wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.9.19
    cli_version: 0.17.3
    framework: lightning
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1741196251
    t:
      1:
      - 1
      - 5
      - 9
      - 41
      - 49
      - 53
      - 55
      - 63
      - 74
      - 80
      - 103
      2:
      - 1
      - 5
      - 9
      - 41
      - 49
      - 53
      - 55
      - 63
      - 74
      - 80
      - 103
      3:
      - 7
      - 13
      - 23
      - 66
      4: 3.9.19
      5: 0.17.3
      8:
      - 4
      - 5
      13: darwin-arm64
    m:
    - 1: trainer/global_step
      6:
      - 3
hidden_size:
  desc: null
  value: 128
num_layers:
  desc: null
  value: 2
lr:
  desc: null
  value: 0.001
