wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.9.19
    cli_version: 0.17.3
    framework: lightning
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1741196152
    t:
      1:
      - 1
      - 5
      - 9
      - 41
      - 49
      - 53
      - 55
      - 63
      - 74
      - 80
      - 103
      3:
      - 13
      - 23
      4: 3.9.19
      5: 0.17.3
      8:
      - 5
      13: darwin-arm64
